services:
  - type: web
    name: whatsapp-gemini-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: GEMINI_API_KEY
        value: TU_CLAVE_DE_API_GEMINI
      - key: ULTRAMSG_INSTANCE
        value: instance120157
      - key: ULTRAMSG_TOKEN
        value: ob3qn8omp769ev8o
